<a href="https://colab.research.google.com/github/Karan1914/100DaysOfDataScience/blob/master/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
corpus = '    This is my duMmy Dataset. It is part of taught course on text mining.   '


In [3]:
#1. to lowercase
corpus = corpus.lower()

corpus

'    this is my dummy dataset. it is part of taught course on text mining.   '

In [4]:
#2 remove white spaces
corpus = corpus.strip()

corpus

'this is my dummy dataset. it is part of taught course on text mining.'

In [6]:
#3 remove punctuations
from string import punctuation as punc
punc

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [7]:
for ch in corpus:
    if ch in punc:
        corpus = corpus.replace(ch, '')
        
print(corpus)  

this is my dummy dataset it is part of taught course on text mining


In [9]:
#4 stop words removal
from sklearn.feature_extraction.stop_words import ENGLISH_STOP_WORDS
print(ENGLISH_STOP_WORDS)



frozenset({'ltd', 'its', 'mill', 'those', 'because', 'describe', 'else', 'his', 'call', 'hers', 'etc', 'indeed', 'put', 'ourselves', 'here', 'anywhere', 'sometimes', 'bill', 'perhaps', 'six', 'noone', 'becoming', 'can', 'him', 'whereby', 'fire', 'onto', 'last', 'otherwise', 'whose', 'part', 'even', 'next', 'was', 'again', 'there', 'front', 'my', 'show', 'too', 'toward', 'made', 'alone', 'except', 'full', 'one', 'all', 'same', 'anything', 'thence', 'nor', 'that', 'such', 'under', 'empty', 'within', 'themselves', 'others', 'take', 'amoungst', 'co', 'before', 'done', 'it', 'than', 'thereby', 'therefore', 'anyway', 'but', 'about', 'nothing', 'nowhere', 'mostly', 'throughout', 'during', 'were', 'someone', 'something', 'so', 'the', 'am', 'cannot', 'over', 'yourself', 'well', 'still', 'wherever', 'beside', 'beyond', 'if', 'why', 'get', 'less', 'must', 'very', 'namely', 'when', 'their', 'thereupon', 'in', 'several', 'thru', 'will', 'and', 'of', 'once', 'eleven', 'third', 'should', 'side', 'ple

In [10]:
words = corpus.split(' ')

for word in words:
    if word in ENGLISH_STOP_WORDS:
        words.remove(word)
        
print(words)  

['is', 'dummy', 'dataset', 'is', 'of', 'taught', 'course', 'text', 'mining']


In [11]:
corpus = '<html><head></head><body><h1>Paragraph Heading</h1><p>This is some text. <a href="">The original price was $500 but now only USD250 </a> This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is <em>some text.</em> <strong>This is some text.</strong> This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. </p></body></html>'
print('Raw data: ', corpus)


Raw data:  <html><head></head><body><h1>Paragraph Heading</h1><p>This is some text. <a href="">The original price was $500 but now only USD250 </a> This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is <em>some text.</em> <strong>This is some text.</strong> This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. </p></body></html>


In [12]:
import re
tags = re.compile(r'<.*?>')
corpus = tags.sub('', corpus)

prices = re.compile(r'(USD|\$)[0-9]+')
corpus = prices.sub('', corpus)

print('normalized data: ', corpus)

normalized data:  Paragraph HeadingThis is some text. The original price was  but now only   This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. This is some text. 


In [13]:
#Stemming
from nltk.stem import PorterStemmer
pstemmer = PorterStemmer()
for i in range(0, len(words)):
    words[i] = pstemmer.stem(words[i])
print(words)

 

['is', 'dummi', 'dataset', 'is', 'of', 'taught', 'cours', 'text', 'mine']


In [33]:
import nltk
#nltk.download('all')


In [17]:
#Lemmatization
from nltk.stem import WordNetLemmatizer
lemma = WordNetLemmatizer()
for i in range(0, len(words[i])):
    words[i] = lemma.lemmatize(words[i], pos='v')
print(words) 

['be', 'dummi', 'dataset', 'is', 'of', 'taught', 'cours', 'text', 'mine']


In [19]:

corpus = 'i like this table in my room'
words = corpus.split(' ')

from nltk import pos_tag
tags = pos_tag(words)

for i in range(0, len(tags)):
    if tags[i][1] == 'DT':
        print(tags[i])

('this', 'DT')


In [21]:
corpus = 'He owes me 22.50 dollars. Which is due by the next day.'
print(corpus.split('.'))

from nltk.tokenize import sent_tokenize, word_tokenize
print(sent_tokenize(corpus))



['He owes me 22', '50 dollars', ' Which is due by the next day', '']
['He owes me 22.50 dollars.', 'Which is due by the next day.']


In [22]:
for sent in sent_tokenize(corpus):
    print(word_tokenize(sent))

['He', 'owes', 'me', '22.50', 'dollars', '.']
['Which', 'is', 'due', 'by', 'the', 'next', 'day', '.']


In [24]:

import requests
session = requests.Session()
session.trust_env = False

#proxies = {
#          'http' : 'http://192.168.12.84:808',
#          'https' : 'https://192.168.23.38:808'
#       }

response = session.get('https://en.wikipedia.org/wiki/Natural_language_processing')
print(response)


<Response [200]>


In [32]:
#print(response.text)

### Types of Text Representation
  - Frequency based Bag of words
  - Binary Based Bag of Words
  - Log Frequency Distribution
  - TF- IDF Frequency Distribution

    - TF - IDF = TF * IDF
      - TF = Count (w in Doc) // Doc Size
      - IDF = log | M + 1 // k |
        - M : Total Number of Documents in a Dataset
        - k : Documents that have this particular word

        - IDF is important to reduce the impact of frequently occuring words


In [26]:
# Frequency Based Distribution for One Document 

corpus = ['text text mining is interesting']

from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer()

X = vec.fit_transform(corpus)

print(X.toarray())
print(vec.get_feature_names())
print(len(vec.get_feature_names()))
print(vec.vocabulary_)

[[1 1 1 2]]
['interesting', 'is', 'mining', 'text']
4
{'text': 3, 'mining': 2, 'is': 1, 'interesting': 0}


In [27]:

# Frequency Based Distribution for Multi Document 

corpus = ['text text mining is interesting',
          'text mining is the same as data mining',
          'text and data mining have few differences']

from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer()

X = vec.fit_transform(corpus)

print(X.toarray())
print(vec.get_feature_names())
print(len(vec.get_feature_names()))
print(vec.vocabulary_)

[[0 0 0 0 0 0 1 1 1 0 2 0]
 [0 1 1 0 0 0 0 1 2 1 1 1]
 [1 0 1 1 1 1 0 0 1 0 1 0]]
['and', 'as', 'data', 'differences', 'few', 'have', 'interesting', 'is', 'mining', 'same', 'text', 'the']
12
{'text': 10, 'mining': 8, 'is': 7, 'interesting': 6, 'the': 11, 'same': 9, 'as': 1, 'data': 2, 'and': 0, 'have': 5, 'few': 4, 'differences': 3}


In [30]:
# Updating Parameters
# Binary Frequency Based Distribution for Multi Document 

corpus = ['text text mining is interesting',
          'text mining is the same as data mining',
          'text and data mining have few differences']

from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer(binary = 'true', max_df = 2, min_df = 2, max_features =2, ngram_range=(1,3))

X = vec.fit_transform(corpus)
print(X.toarray())
print(vec.get_feature_names())
print(len(vec.get_feature_names()))
print(vec.vocabulary_)

# Parameters name : 1) Binary = True
# 2) max_df = 2  :  maximum document frequency
# 3) min_df = 2   : minimum document frequency
# max_features = 2 :  Best n features in all documents
# ngram_range = (1,3) : Unigrams, Bigrams, Trigrams

[[0 0]
 [1 1]
 [1 1]]
['data', 'data mining']
2
{'data': 0, 'data mining': 1}


In [31]:
# TF-IDF Frequency Based Distribution for Multi Document 

corpus = ['text text mining is interesting',
          'text mining is the same as data mining',
          'text and data mining have few differences']

from sklearn.feature_extraction.text import TfidfVectorizer

vec = TfidfVectorizer()
X = vec.fit_transform(corpus)
print(X.toarray())
print(vec.get_feature_names())
print(len(vec.get_feature_names()))
print(vec.vocabulary_)

[[0.         0.         0.         0.         0.         0.
  0.54861178 0.4172334  0.32401895 0.         0.64803791 0.        ]
 [0.         0.41166084 0.31307868 0.         0.         0.
  0.         0.31307868 0.48626704 0.41166084 0.24313352 0.41166084]
 [0.43535684 0.         0.3311001  0.43535684 0.43535684 0.43535684
  0.         0.         0.25712876 0.         0.25712876 0.        ]]
['and', 'as', 'data', 'differences', 'few', 'have', 'interesting', 'is', 'mining', 'same', 'text', 'the']
12
{'text': 10, 'mining': 8, 'is': 7, 'interesting': 6, 'the': 11, 'same': 9, 'as': 1, 'data': 2, 'and': 0, 'have': 5, 'few': 4, 'differences': 3}


In [ ]:


# Dummy dataset Import and performing operations

corpus = open('E:\\dataset.txt').read()
docs = corpus.split('\n')

input_X, y = [], []

for doc in docs:
    i, l = doc.split(':')
    input_X.append(i.strip())
    y.append(l.strip())

from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer(binary = 'true', max_df = 2, min_df = 2, max_features =2, ngram_range=(1,3))
X = vec.fit_transform(input_X)

print(X.toarray())
print(vec.get_feature_names())
print(len(vec.get_feature_names()))
print(vec.vocabulary_)

### Lazy or Instance base machine Learning Models : KNN : Uses data to find the pattern 
### Model Based : Doesnot require data to find the pattern

  - Non Parametric :  Takes more time , but comes up with a solution : Do not look into the data with a predefined solution in a mind, hence comes up with a dynamic solution
  - Parametric are fast 

In [ ]:


#reading data from the file
corpus = open('E:\\dataset.txt').read()

#separating data into documents and labels.
docs = corpus.split('\n')
X, y = [], []
for doc in docs:
    i, l = doc.split(':')
    X.append(i.strip())
    y.append(l.strip())

#Structure input data
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer()
matrix_X = vec.fit_transform(X)



In [ ]:
#Applying K-Nearest Neighbors classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(matrix_X[:5], y[:5])
print('KNN Classifier, Label: ' + str(knn.predict(matrix_X[5])))
print('KNN Classifier, prob.' + str(knn.predict_proba(matrix_X[5])))

#Applying Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
nbc = MultinomialNB()
nbc.fit(matrix_X[:5], y[:5])
print('Naive Bayes Classifier, Label: ' + str(nbc.predict(matrix_X[5])))
print('Naive Bayes Classifier, prob.' + str(nbc.predict_proba(matrix_X[5])))

#Applying Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(matrix_X[:5], y[:5])
print('Decision Tree Classifier, Label: ' + str(dtc.predict(matrix_X[5])))
print('Decision Tree Classifier, prob.' + str(dtc.predict_proba(matrix_X[5])))

#Applying Linear Classifier
from sklearn.linear_model import SGDClassifier
lc = SGDClassifier()
lc.fit(matrix_X[:5], y[:5])
print('Linear Classifier, Label: ' + str(lc.predict(matrix_X[5])))
#Linear Classifier doesn't have the probability value as it operates differently


In [ ]:
# Tuning With parameters


#Applying K-Nearest Neighbors classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3, algorithm = 'kd_tree', weights = 'distance')
knn.fit(matrix_X[:5], y[:5])
print('KNN Classifier, Label: ' + str(knn.predict(matrix_X[5])))
print('KNN Classifier, prob.' + str(knn.predict_proba(matrix_X[5])))

#Applying Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
nbc = MultinomialNB(alpha = 0.2, fit_prior = False, class_prior = [0.6, 0.4])
nbc.fit(matrix_X[:5], y[:5])
print('Naive Bayes Classifier, Label: ' + str(nbc.predict(matrix_X[5])))
print('Naive Bayes Classifier, prob.' + str(nbc.predict_proba(matrix_X[5])))

#Applying Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(max_depth = 2)
dtc.fit(matrix_X[:5], y[:5])
print('Decision Tree Classifier, Label: ' + str(dtc.predict(matrix_X[5])))
print('Decision Tree Classifier, prob.' + str(dtc.predict_proba(matrix_X[5])))

#Applying Linear Classifier
from sklearn.linear_model import SGDClassifier
lc = SGDClassifier(max_iter = 1000)
lc.fit(matrix_X[:5], y[:5])
print('Linear Classifier, Label: ' + str(lc.predict(matrix_X[5])))
#Linear Classifier doesn't have the probability value as it operates differently

In [ ]:
# DATA TAken from UCI repository : Badges data : 294 instances
# https://archive.ics.uci.edu/ml/datasets/Badges

# Predicting Badges (+, - )

corpus = open('E:\\badges.data').read()
docs = corpus.split('\n')
X, y = [], [] 
for doc in docs:
    l = doc[:1]
    i = doc[2:]
    X.append(i)
    y.append(l)
from sklearn.feature_extraction.text import TfidfVectorizer
vec = TfidfVectorizer()
matrix_X = vec.fit_transform(X)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(matrix_X[:290], y[:290])
#predicted labels of the last four documents
print(knn.predict(matrix_X[290:])) 
#prediction probability of the two labels for each of the last four documents
print(knn.predict_proba(matrix_X[290:])) 

In [ ]:
# Predicting Sentiments

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
import pandas as pd
from sklearn.model_selection import train_test_split

#preparing data
raw_data = pd.read_csv("D:\\Datasets\\imdb-dataset-of-50k-movie-reviews\\IMDB Dataset.csv")

review_docs = raw_data.iloc[:, 0]
y = raw_data.iloc[:, 1]

print(set(y))

#structuring data
tfidf = TfidfVectorizer(min_df = 20, max_df = 30000).fit_transform(review_docs)
#print(tfidf)

# Splitting data to training and testing
training_docs, training_y, testing_docs, testing_y = train_test_split(tfidf, y, train_size = 0.8, shuffle = True)

#training model
clf = MultinomialNB().fit(training_docs, training_y)

#predicting labels for last 10 instances
pred_y = clf.predict(testing_docs)
print('Predicted labels: ', clf.predict(testing_docs))

#Actual labels of the last 10 instances
print('Actual labels: ', testing_y)

from sklearn.metrics import accuracy_score

acc = accuracy_score(testing_y, pred_y)


In [ ]:
# K- Fold

corpus = open('E:\\dataset.txt').read()
docs = corpus.split('\n')
X, y = [], []
for doc in docs:
    i, l = doc.split(':')
    X.append(i)
    y.append(l)

from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer()
matrix_X = vec.fit_transform(X)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)

from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
for id_train, id_test in kf.split(matrix_X):
    print('Train', id_train, 'Test', id_test)
    train_X, test_X = matrix_X[id_train], matrix_X[id_test]

In [ ]:

# K-Fold on IMDB data


acc = []

from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)

for train_ids, test_ids in kf.split(tfidf,y):
    
    train_docs, test_docs = tfidf[train_ids], tfidf[test_ids]
    train_y, test_y = y[train_ids], y[test_ids]
    clf = MultinomialNB().fit(train_docs, train_y)
    pred_y = clf.predict(test_docs)
    acc.append(accuracy_score(test_y, pred_y))

total_accuracy = sum(acc)/5
print(total_accuracy)

    

In [ ]:
# Leave one out 

acc = []

from sklearn.model_selection import LeaveOneOut
loo = LeaveOneOut(n_splits = 3)

for train_ids, test_ids in loo.split(tfidf):
    
    train_docs, test_docs = tfidf[train_ids], tfidf[test_ids]
    train_y, test_y = y[train_ids], y[test_ids]
    clf = MultinomialNB().fit(train_docs, train_y)
    pred_y = clf.predict(test_docs)
    acc.append(accuracy_score(test_y, pred_y))

total_accuracy = sum(acc)/5
print(total_accuracy)

In [ ]:
# Putting it altogether

corpus = open('E:\\badges.data').read()
docs = corpus.split('\n')
X, y = [], []
for doc in docs:
    y.append(doc[:1])
    X.append(doc[2:])
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer()
matrix_X = vec.fit_transform(X)

from sklearn.model_selection import KFold
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score

kf = KFold(n_splits = 4)
nb = MultinomialNB()
dt = DecisionTreeClassifier(max_depth = 3)

import numpy as np
y = np.array(y)

f1_nb_score = 0; f1_dt_score = 0
for train_ids, test_ids in kf.split(matrix_X):
    train_X, test_X = matrix_X[train_ids], matrix_X[test_ids]
    train_y, test_y = y[train_ids], y[test_ids]
    nb.fit(train_X, train_y)
    dt.fit(train_X, train_y)
    pred_nb_y = nb.predict(test_X)
    pred_dt_y = dt.predict(test_X)
    f1_nb_score += f1_score(test_y, pred_nb_y, average = 'micro')
    f1_dt_score += f1_score(test_y, pred_dt_y, average = 'micro')
    
print(f1_nb_score/4)
print(f1_dt_score/4)